name: baratito_ui
description: UI kit for baratito.
version: 0.0.1
homepage: https://github.com/baratito/baratito_ui

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  assorted_layout_widgets: ^5.1.3
  auto_size_text: ^3.0.0-nullsafety.0
  cached_network_image: ^3.0.0
  flutter:
    sdk: flutter
  flutter_svg: ^0.23.0+1
  path: ^1.8.0
  provider: ^6.0.0
  shared_preferences: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
  test: ^1.16.8

flutter:
  uses-material-design: true
  assets:
    - assets/logos/

  fonts:
    - family: Poppins
      fonts:
        - asset: lib/fonts/Poppins/Poppins-Regular.ttf
        - asset: lib/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: lib/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
    - family: BaratitoIcons
      fonts:
        - asset: lib/fonts/BaratitoIcons.ttf
